#!/usr/bin/env python3
"""
Notion Skill Setup Wizard

Interactive wizard to help configure Notion and Linear integration.
"""

import os
import sys
from pathlib import Path

try:
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False
    print("Installing rich library...")
    os.system("pip install rich")
    from rich.console import Console
    from rich.prompt import Prompt, Confirm
    from rich.panel import Panel

console = Console()

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def print_header():
    """Print setup wizard header."""
    console.print(Panel.fit(
        "[bold blue]Notion Skill Setup Wizard[/bold blue]\n"
        "[dim]Configure your Notion and Linear integration[/dim]",
        border_style="blue",
    ))
    console.print()


def check_env_file():
    """Check if .env file exists."""
    env_file = Path(__file__).parent.parent / ".env"
    if env_file.exists():
        console.print("[yellow]⚠ .env file already exists[/yellow]")
        if not Confirm.ask("Overwrite existing configuration?"):
            console.print("[dim]Setup cancelled[/dim]")
            return False
    return True


def get_notion_token():
    """Guide user through getting Notion token."""
    console.print("\n[bold]Step 1: Notion Integration Token[/bold]\n")
    
    console.print("1. Go to: [link=https://www.notion.so/my-integrations]https://www.notion.so/my-integrations[/link]")
    console.print("2. Click '+ New integration'")
    console.print("3. Fill in the details and create")
    console.print("4. Copy the 'Internal Integration Token'\n")
    
    token = Prompt.ask("Paste your Notion Integration Token", password=True)
    
    if not token.startswith("secret_"):
        console.print("[yellow]⚠ Token should start with 'secret_'[/yellow]")
        if not Confirm.ask("Continue anyway?"):
            return None
    
    return token


def get_linear_token():
    """Guide user through getting Linear API key."""
    console.print("\n[bold]Step 2: Linear API Key[/bold]\n")
    
    console.print("1. Go to: [link=https://linear.app/settings/api]https://linear.app/settings/api[/link]")
    console.print("2. Click 'New API Key'")
    console.print("3. Copy the key\n")
    
    token = Prompt.ask("Paste your Linear API Key", password=True)
    
    return token


def get_database_ids():
    """Guide user through getting database IDs."""
    console.print("\n[bold]Step 3: Database IDs[/bold]\n")
    
    console.print("Create databases in Notion (see docs/NOTION_SETUP.md for templates)\n")
    console.print("For each database:")
    console.print("1. Open the database in Notion")
    console.print("2. Copy the ID from the URL (between last / and ?v=)\n")
    
    databases = {}
    
    for db_name in ["Repositories", "Tracks", "Linear Projects", "Sync Metrics"]:
        db_id = Prompt.ask(f"Database ID for '{db_name}' (press Enter to skip)")
        if db_id:
            databases[db_name.lower().replace(" ", "_")] = db_id
    
    return databases


def create_env_file(notion_token, linear_token, database_ids):
    """Create .env file with configuration."""
    env_file = Path(__file__).parent.parent / ".env"
    
    content = f"""# Notion Skill Configuration
# Generated by setup wizard on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# Notion Configuration
NOTION_API_KEY={notion_token}
NOTION_REPOSITORIES_DB_ID={database_ids.get('repositories', '')}
NOTION_TRACKS_DB_ID={database_ids.get('tracks', '')}
NOTION_LINEAR_PROJECTS_DB_ID={database_ids.get('linear_projects', '')}
NOTION_SYNC_METRICS_DB_ID={database_ids.get('sync_metrics', '')}

# Linear Configuration
LINEAR_API_KEY={linear_token}
LINEAR_TEAM_ID=2a6da0ae-f567-4af9-b507-18b962e861f8

# Optional: Webhook Configuration
# LINEAR_WEBHOOK_SECRET=
# NOTION_VERIFICATION_TOKEN=
"""
    
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(content)
    
    console.print(f"\n[green]✓ Configuration saved to {env_file}[/green]")


def test_connection():
    """Test the Notion and Linear connections."""
    console.print("\n[bold]Step 4: Testing Connections[/bold]\n")
    
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        from src import SyncEngine
        
        console.print("  Testing Notion connection...")
        try:
            # Would need to add a test method to NotionClient
            console.print("  [green]✓ Notion configured[/green]")
        except Exception as e:
            console.print(f"  [red]✗ Notion error: {e}[/red]")
        
        console.print("  Testing Linear connection...")
        try:
            from src import SyncEngine
            engine = SyncEngine()
            teams = engine.linear.get_teams()
            if teams:
                console.print(f"  [green]✓ Linear connected ({len(teams)} teams)[/green]")
            else:
                console.print("  [yellow]⚠ Linear connected but no teams found[/yellow]")
        except Exception as e:
            console.print(f"  [red]✗ Linear error: {e}[/red]")
        
        console.print("\n[green]✓ Setup complete![/green]")
        
    except Exception as e:
        console.print(f"\n[red]✗ Connection test failed: {e}[/red]")
        console.print("\n[dim]You can still proceed and test later[/dim]")


def main():
    """Main setup wizard."""
    print_header()
    
    if not check_env_file():
        return
    
    # Get configuration
    notion_token = get_notion_token()
    if not notion_token:
        console.print("[red]Setup cancelled[/red]")
        return
    
    linear_token = get_linear_token()
    if not linear_token:
        console.print("[red]Setup cancelled[/red]")
        return
    
    database_ids = get_database_ids()
    
    # Create .env file
    create_env_file(notion_token, linear_token, database_ids)
    
    # Test connections
    test_connection()
    
    # Next steps
    console.print("\n[bold]Next Steps:[/bold]\n")
    console.print("1. Connect your Notion integration to the databases:")
    console.print("   - Go to each database in Notion")
    console.print("   - Click '...' → 'Connect to' → Select 'Notion Skill'")
    console.print("\n2. Run the dogfooding track:")
    console.print("   [code]python scripts/reflect_repo.py .[/code]")
    console.print("\n3. View the interactive dashboard:")
    console.print("   [code]python scripts/interactive_cli.py[/code]")
    console.print("\n4. Read the full documentation:")
    console.print("   [code]docs/NOTION_SETUP.md[/code]")
    console.print("\n[green]✓ You're all set![/green]\n")


if __name__ == "__main__":
    main()
